=== Zastrozhyn/JWD-XMLParsing/resources/deposites.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.zastr.by/deposites"
        xmlns:tns="http://www.zastr.by/deposites"
        elementFormDefault="qualified">
    <element name="deposit" type="tns:Deposit" abstract="true"/>
    <element name="recurring-deposit" type="tns:Recurring-deposit" substitutionGroup="tns:deposit"/>
    <element name="saving-deposit" type="tns:Saving-deposit" substitutionGroup="tns:deposit"/>
    <element name="current-account-deposit" type="tns:Current-account-deposit" substitutionGroup="tns:deposit"/>
     <element name="deposites">
       <complexType>
           <sequence>
               <element ref="tns:deposit"
                        minOccurs="1"
                        maxOccurs="unbounded"/>
           </sequence>
       </complexType>
    </element>
    <complexType name="Deposit">
        <sequence>
            <element name="bank-name" type="string"/>
            <element name="country" type="tns:Country"/>
            <element name="depositor" type="tns:Depositor"/>
            <element name="account-id" type="tns:Account-id"/>
            <element name="amount-on-deposit" type="long"/>
            <element name="profitability" type="byte"/>
        </sequence>
        <attribute name="revocable" use="required" type="boolean"/>
        <attribute name="website" use="optional" type="string"/>
    </complexType>
    
    <complexType name="Recurring-deposit">
        <complexContent>
            <extension base="tns:Deposit">
                <sequence>
                    <element name="service-cost" type="integer"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    
    <complexType name="Saving-deposit">
        <complexContent>
            <extension base="tns:Deposit">
                <sequence>
                    <element name="expiration-date" type="date"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    
    <complexType name="Current-account-deposit">
        <complexContent>
            <extension base="tns:Deposit">
                <sequence>
                    <element name="credit-limit" type="tns:Credit-limit"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
             
    <simpleType name="Country">
        <restriction base="string">
            <enumeration value="US"/>
            <enumeration value="DE"/>
            <enumeration value="GB"/>
            <enumeration value="BY"/>
            <enumeration value="RU"/>
            <enumeration value="FR"/>
        </restriction>
    </simpleType>
     <simpleType name="Account-id">
        <restriction base="ID">
            <pattern value="id\d{4}"/>
        </restriction>
    </simpleType>
    <simpleType name="Age">
        <restriction base="byte">
            <minInclusive value="18"/>
            <maxInclusive value="100"/>
        </restriction>
    </simpleType>
    <simpleType name="Credit-limit">
        <restriction base="long">
            <minInclusive value="0"/>
            <maxInclusive value="10000"/>
        </restriction>
    </simpleType>
    <complexType name="Depositor">
        <sequence>
            <element name="name" type="string"/>
            <element name="age" type="tns:Age"/>
            <element name="phone" type="string"/>
        </sequence>
    </complexType>
</schema>

=== Zastrozhyn/JWD-XMLParsing/src/main/resources/deposites.xml
<?xml version="1.0" encoding="UTF-8"?>
<deposites xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://www.zastr.by/deposites"
           xsi:schemaLocation="http://www.zastr.by/deposites deposites.xsd">
        
        <saving-deposit id="1" website="http:www.jpmorganchase.com">
             <bank-name>JPMorgan Chase</bank-name>
             <country>US</country>
             <depositor>
	             <name>Ivanov</name>
	             <age>20</age>
	             <phone>+375292221133</phone>
             </depositor>
             <account-id>1234 5678 7890</account-id>
             <amount-on-deposit>2000</amount-on-deposit>
             <profitability>4</profitability>
             <expiration-date>2023-10-10</expiration-date>
        </saving-deposit>
        
        <recurring-deposit id="2" website="http:www.hsbc.com">
            <bank-name>HSBC</bank-name>
            <country>GB</country>
            <depositor>
           		 <name>Petrov</name>
           		 <age>22</age>
	             <phone>+375292201133</phone>
            </depositor>
            <account-id>2234 5678 7891</account-id>
            <amount-on-deposit>5200</amount-on-deposit>
            <profitability>0</profitability>
            <service-cost>10</service-cost>
        </recurring-deposit>
        
        <recurring-deposit id="3" website="http:www.bankofamerica.com">
	        <bank-name>Bank of America</bank-name>
     	    <country>US</country>
	        <depositor>
	        	 <name>Sidorov</name>
	        	 <age>30</age>
	             <phone>+375292223130</phone>
	        </depositor>
	        <account-id>3234 5678 7892</account-id>
	        <amount-on-deposit>2500</amount-on-deposit>
	        <profitability>0</profitability>
	        <service-cost>10</service-cost>
        </recurring-deposit>
        
        <saving-deposit id="4" website="http:www.db.com">
	        <bank-name>	Deutsche Bank</bank-name>
    	    <country>DE</country>
	        <depositor>
	      	     <name>Zaicev</name>
	      	     <age>30</age>
	             <phone>+375292221193</phone>
	        </depositor>
	        <account-id>4234 5678 7893</account-id>
	        <amount-on-deposit>33000</amount-on-deposit>
	        <profitability>3</profitability>
	        <expiration-date>2023-01-10</expiration-date>
        </saving-deposit>
        
        <current-account-deposit id="5">
	        <bank-name>Alfa Bank</bank-name>
	        <country>BY</country>
	        <depositor>
	             <name>Pygachev</name>
	             <age>32</age>
	             <phone>+375292224433</phone>
	        </depositor>
	        <account-id>5234 5678 7894</account-id>
	        <amount-on-deposit>4100</amount-on-deposit>
	        <profitability>2</profitability>
	        <expiration-date>2022-12-09</expiration-date>
	        <credit-limit>1000</credit-limit>
        </current-account-deposit>
        
        <saving-deposit id="6">
	        <bank-name>Priorbank</bank-name>
	        <country>BY</country>
	        <depositor>
	  	         <name>Bregnev</name>
	  	         <age>50</age>
	             <phone>+375294221133</phone>
	        </depositor>
	        <account-id>6234 5678 7890</account-id>
	        <amount-on-deposit>51000</amount-on-deposit>
 	        <profitability>7</profitability>
	        <expiration-date>2022-12-11</expiration-date>
        </saving-deposit>
        
        <recurring-deposit id="7" website="http:	www.citigroup.com">
	        <bank-name>Citigroup</bank-name>
	        <country>US</country>
	        <depositor>
	             <name>BlinovI</name>
	             <age>40</age>
	             <phone>+375292227133</phone>
	        </depositor>
	        <account-id>7234 5678 7890</account-id>
	        <amount-on-deposit>243000</amount-on-deposit>
	        <profitability>0</profitability>
	        <service-cost>10</service-cost>
        </recurring-deposit>
        
        <saving-deposit id="8" website="http:www.hsbc.com">
	        <bank-name>HSBC</bank-name>
	        <country>GB</country>
	        <depositor>
	             <name>Pechkin</name>
	             <age>30</age>
	             <phone>+375292021133</phone>
	        </depositor>
	        <account-id>8234 5678 7890</account-id>
	        <amount-on-deposit>2100</amount-on-deposit>
	        <profitability>2</profitability>
	        <expiration-date>2022-02-01</expiration-date>
        </saving-deposit>
        
        <current-account-deposit id="9">
	        <bank-name>MTBank</bank-name>
	        <country>BY</country>
	        <depositor>
	             <name>Korneev</name>
	             <age>40</age>
	             <phone>+375292721133</phone>
	        </depositor>
	        <account-id>9234 5678 7890</account-id>
	        <amount-on-deposit>32000</amount-on-deposit>
	        <profitability>2</profitability>
	        <expiration-date>2022-12-12</expiration-date>
	        <credit-limit>5000</credit-limit>
        </current-account-deposit>
        
        <recurring-deposit id="10">
	        <bank-name>Sberbank</bank-name>
	        <country>RU</country>
	        <depositor>
	             <name>Konev</name>
	             <age>21</age>
	             <phone>+375292551133</phone>
	        </depositor>
	        <account-id>1134 5678 7890</account-id>
	        <amount-on-deposit>97000</amount-on-deposit>
	        <profitability>0</profitability>
	        <service-cost>10</service-cost>
        </recurring-deposit>
        
        <saving-deposit id="11" website="http:www.jpmorganchase.com">
	        <bank-name>JPMorgan Chase</bank-name>
	        <country>US</country>
	        <depositor>
	             <name>Karpov</name>
	             <age>70</age>
	             <phone>+375292511133</phone>
	        </depositor>
	        <account-id>2134 5678 7890</account-id>
	        <amount-on-deposit>1000</amount-on-deposit>
	        <profitability>3</profitability>
	        <expiration-date>2022-12-10</expiration-date>
        </saving-deposit>
        
        <recurring-deposit id="12" website="http:www.db.com">
	        <bank-name>	Deutsche Bank</bank-name>
	        <country>DE</country>
	        <depositor>
	             <name>Levitov</name>
	             <age>25</age>
	             <phone>+375292288133</phone>
	        </depositor>
	        <account-id>3134 5678 7890</account-id>
	        <amount-on-deposit>9000</amount-on-deposit>
	        <profitability>0</profitability>
	        <service-cost>10</service-cost>
        </recurring-deposit>
        
        <saving-deposit id="13" website="http:www.hsbc.com">
	        <bank-name>HSBC</bank-name>
	        <country>GB</country>
	        <depositor>
	             <name>Fedorov</name>
	             <age>27</age>
	             <phone>+375292321133</phone>
	        </depositor>
	        <account-id>4134 5678 7890</account-id>
	        <amount-on-deposit>260000</amount-on-deposit>
	        <profitability>4</profitability>
	        <expiration-date>2023-12-12</expiration-date>
        </saving-deposit>
        
        <saving-deposit id="14">
	        <bank-name>Priorbank</bank-name>
	        <country>BY</country>
	        <depositor>
	             <name>Kopytov</name>
	             <age>19</age>
	             <phone>+375292001133</phone>
	        </depositor>
	        <account-id>5134 5678 7890</account-id>
	        <amount-on-deposit>13000</amount-on-deposit>
	        <profitability>9</profitability>
	        <expiration-date>2024-10-12</expiration-date>
        </saving-deposit>
        
        <current-account-deposit id="15">
	        <bank-name>Alfa bank</bank-name>
	        <country>BY</country>
	        <depositor>
	             <name>Shwed</name>
	             <age>51</age>
	             <phone>+375292229833</phone>
	        </depositor>
	        <account-id>6134 5678 7890</account-id>
	        <amount-on-deposit>5000</amount-on-deposit>
	        <profitability>1</profitability>
	        <expiration-date>2021-12-12</expiration-date>
	        <credit-limit>1000</credit-limit>
        </current-account-deposit>
        
        <saving-deposit id="16" website="http:www.bnpparibas.com">
	        <bank-name>BNP Paribas</bank-name>
	        <country>FR</country>
	        <depositor>
	             <name>Shipov</name>
	             <age>41</age>
	             <phone>+375292278133</phone>
	        </depositor>
	        <account-id>7134 5678 7890</account-id>
	        <amount-on-deposit>6000</amount-on-deposit>
	        <profitability>3</profitability>
	        <expiration-date>2024-05-10</expiration-date>
        </saving-deposit>
</deposites>
